project:
  type: website
  output-dir: _site

website:
  title: "blech_clust Documentation"
  description: "Python and R based code for clustering and sorting electrophysiology data"
  repo-url: https://github.com/katzlabbrandeis/blech_clust
  repo-actions: [edit, issue]

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Getting Started"
        file: getting-started.qmd
      - text: "API Reference"
        file: reference/index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
    right:
      - icon: github
        href: https://github.com/katzlabbrandeis/blech_clust
        aria-label: GitHub

  sidebar:
    - id: reference
      title: "API Reference"
      contents:
        - reference/index.qmd
        - section: "Overview Guides"
          contents:
            - reference/core-pipeline.qmd
            - reference/utilities.qmd
            - reference/ephys-data.qmd
            - reference/qa-tools.qmd
            - reference/emg-analysis.qmd
        - text: "---"
        - section: "Auto-Generated API"
          contents:
            - reference/api-index.qmd

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap

quartodoc:
  # Source directory relative to docs/
  source_dir: ../utils
  
  # Package name (null for non-package structure)
  package: null
  
  # Output directory for generated docs
  dir: reference/api
  
  # Sidebar configuration
  sidebar: reference/_sidebar.yml
  
  # Renderer and parser
  renderer:
    style: markdown
    show_signature_annotations: true
  parser: numpy
  
  # Options applied to all content
  options:
    include_private: false
    include_imports: false
    include_empty: false
    signature_name: short
  
  sections:
    - title: "Core Utilities"
      desc: "Essential utility functions and classes from blech_utils"
      contents:
        - name: blech_utils.Tee
        - name: blech_utils.path_handler
        - name: blech_utils.imp_metadata
        - name: blech_utils.entry_checker
