name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "quartodoc<0.3" "griffe<1.0"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.6.39'

      - name: Build API documentation with quartodoc
        run: |
          cd docs
          python -m quartodoc build

      - name: Render documentation with Quarto
        run: |
          cd docs
          quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    # Only deploy on push to master, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
